### ISSUE TITLE
Center footer in tablet mode (max-width: 860px)

### ISSUE THREAD

**Issue by juvarabrera** [gdgphilippines/devfest2018#12]
### Description

Center the content of footer including gdgph logo and media icons

### Expected outcome

GDGPH logo and media icons centered if max-width is 860px

### Actual outcome

The GDGPH logo and media icons is aligned to the left

### Steps to reproduce

1. Zoom in until page width is below 860px

### Possible Implementation

@media and screen (max-width: 860px) {
    contents of footer { 
       text-align: center;
    }
}

### Browsers Affected

- [x ] Chrome
- [ x] Firefox
- [ x] Safari 11
- [ x] Safari 10
- [ x] Safari 9
- [ x] Edge
- [ x] IE 11

**Comment by tjmonsi** [comment]
Will close this one for now.   Please follow the issue template

**Comment by juvarabrera** [comment]
Updated. Hope that helps :)
