### ISSUE TITLE
Create Speaker List Page Data

### ISSUE THREAD

**Issue by kuuuurt** [gdgphilippines/devfest2018#32]
### Description
Populate Firebase with Speaker Data

Add the speaker list data in table **speakers-list**

Get data from **insert name here** then populate Firebase according to Speaker Model

### Speaker Model for List 
- speakerId
- name
- affiliation
- country

required by #30 
required by #33  

### Expected outcome
1. The speakers data should be in Firebase

**Comment by tjmonsi** [comment]
Adding activity
