### ISSUE TITLE
Create Speaker Detail Page Data

### ISSUE THREAD

**Issue by kuuuurt** [gdgphilippines/devfest2018#36]
### Description
Populate Firebase with Speaker Data

Add the speaker's detail data in table **speakers**
This is the base table for speakers. All tables duplicating speaker data should get updates from this table

Get data from insert name here then populate Firebase according to Speaker Model

### Speaker Model
- speakerId
- name
- affiliation
- position
- city
- country
- talks [array of ids]

required by #34  
required by #37   

### Expected outcome
1. The speaker's detail data should be in Firebase

**Comment by tjmonsi** [comment]
Adding activity
