### ISSUE TITLE
Site Revision

### ISSUE THREAD

**Issue by jielynnd** [gdgphilippines/devfest2018#48]
PROPOSED REVISION:
Progress: Waiting for mockup. Still subject to change.
![image](https://user-images.githubusercontent.com/17779547/45765475-b2125780-bc67-11e8-8a0c-95c0753d1006.png)

link: https://docs.google.com/document/d/1bxF0qEHczVboNkC4wOvQiJDN0vf3GEgSoPVEjy_zCvs/edit

**Comment by juvarabrera** [comment]
What do you mean by Feedback? Do you mean testimonials from participants/speakers last year?

**Comment by juvarabrera** [comment]
This is awesome. Thanks Jielynn

**Comment by jielynnd** [comment]
Please refer to this link: link: https://docs.google.com/document/d/1bxF0qEHczVboNkC4wOvQiJDN0vf3GEgSoPVEjy_zCvs/edit

for full documentation. Thanks @juvarabrera

**Comment by juvarabrera** [comment]
Pwede natin ichange to Testimonials?

**Comment by tjmonsi** [comment]
Can we follow format of the issue? (Sorry OC). Each page should have its own issue?
