### ISSUE TITLE
Additional parts in the homepage

### ISSUE THREAD

**Issue by tjmonsi** [gdgphilippines/devfest2018#50]
### General Info
Add the following parts in the site:
- Download primer
- buying options
- ticket perks
- feedback section
- about devfest section
- stat section

### Expected Behavior
![image](https://user-images.githubusercontent.com/2645718/46122377-e7f8a280-c24a-11e8-8008-bbeb3f83bf66.png)
![image](https://user-images.githubusercontent.com/2645718/46122381-ecbd5680-c24a-11e8-88a3-beba80ee9154.png)
![image](https://user-images.githubusercontent.com/2645718/46122385-f1820a80-c24a-11e8-9cbc-85286cd36106.png)

### Criteria for Acceptability

1.
2.
3.
4.

**Comment by tjmonsi** [comment]
@lucky8548875 man, i want to say na you did good on that white curved part. :)

**Comment by stephenjohndev** [comment]
may issue din po pala sir sa ultra large screens (1440px+)
![image](https://user-images.githubusercontent.com/24974847/46513177-f9b0fa00-c889-11e8-9870-a8c3fd8311a6.png)
